### ISSUE TITLE
Keep always visible - Show pin/unpin toggle

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1094]
Should these two really be possible to use at the same time? So now i can close the Side slider but `Keep always visible` is still set to Yes. If i set `Keep always visible` to Yes the other option should not be available.
So now i can close the Side slider but as soon as i do anything on the page the Side slider get visible again. The behavior is very weird. Try playing around with it and you will see.

**Comment by Sopor-** [comment]
Look here:

![image](https://user-images.githubusercontent.com/5789283/38167456-63c9dd1e-3535-11e8-80a7-4e62396cdd00.png)

**Comment by qooob** [comment]
You're not playing real-life situation.

One could be setting the slider to always fixed, and might want to have it unpined for some reason - there is also the possibility the possibility for it.

Configuration page reflects almost all possible dependencies but this particular one not. The reason is, that the slider is still fixed technically, even though it's unpined.
