### ISSUE TITLE
Error: 500 - Perl execution failed - Undefined subroutine ...

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1609]
Is this normal to get when updating Webmin?
![image](https://user-images.githubusercontent.com/5789283/181799263-6df8ce4e-9152-4133-9d6e-895095f4a1f1.png)

Webmin 1.991 to 1.998
AT 19.91.3 to 19.98

**Comment by Sopor** [comment]
I saw some other issues about AT for unreleased Webmin, but i haven't installed any AT with that warning you get when you update AT.

**Comment by iliajie** [comment]
Well, somewhat expected, and not an issue and further upgrades starting from 1.998 won't display it ever again.

The files on the disk are being updated and background status collection tries to load `stats.cgi` and fails due to dependency failure. This is not a problem and can be ignored.

However, I expected that majority of systems won't see this message already, even when upgrading to 1.998 but it seems that the disks in questions are pretty slow, as it takes more than 1 second (default stats collection interval) to update package files., i.e. `authentic-theme/stats.cgi` gets update, while `webmin/web-lib-funcs.pl` is not.

There is nothing can be done this time.

**Comment by Sopor** [comment]
> but it seems that the disks in questions are pretty slow

It is an SSD M.2 and it has the same speed as an SSD connected to SATA. It is not fast as an SSD NVMe, though.

**Comment by iliajie** [comment]
That sounds like fast enough.

I see what we can actually do here - https://github.com/webmin/authentic-theme/commit/f94b9ddbd492de66503727a5f3e944843c54a56e.

I, unfortunately didn't foreseen and expect this obvious issue to popup. It worked for me instantaneously and I missed the fact that it could happen on slower machines.

There are dozens of interrelated variables to consider!

Thanks for reporting!

**Comment by war59312** [comment]
Just happened to me on an upgrade to 20.01.

Glad nothing to worry about.

The full error BTW:

```
HTTP/1.0 500 Perl execution failed Server: MiniServ/1.999 Date: Sat, 3 Sep 2022 13:14:29 GMT Content-type: text/html; Charset=utf-8 Connection: close
ERROR — PERL EXECUTION FAILED
Undefined subroutine &webmin::get_webmin_full_version called at /usr/share/webmin/webmin/webmin-lib.pl line 1260.
```
