### ISSUE TITLE
uptracker.cgi displays HTML in size field

### ISSUE THREAD

**Issue by michaelbaisch** [webmin/authentic-theme#1692]
Hello,

I've noticed an issue where uptracker.cgi is used, specifically an unintended display of HTML tags in the size field. This issue can be observed in various contexts, such as when uploading a package in the software module or using an upload parameter in a custom module. It's most easily visible with larger files, as the pop-up window remains open for an extended period. I'm opening an issue here because this does not occur with the gray theme, but it does with the authentic theme.

![Screenshot 2024-01-16 at 10 07 30](https://github.com/webmin/authentic-theme/assets/1899691/2d6a175c-02cd-4d64-9bea-ca6c36d099ea)
![Screenshot 2024-01-16 at 10 08 43](https://github.com/webmin/authentic-theme/assets/1899691/7893a335-561c-40fb-9305-d5ed3eb5ec5d)

I suspect that [theme_nice_size_local](https://github.com/webmin/authentic-theme/blob/master/authentic-funcs.pl#L258C5-L258C26) outputs the size with span tags, and in uptracker, these tags are escaped [here](https://github.com/webmin/webmin/blob/master/uptracker.cgi#L93).

Greetings

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up! The problem is actually that the theme did't fully replace `uptracker.cgi` upload tracker.

The latest commit adds support for it.

Example:


![image](https://github.com/webmin/authentic-theme/assets/4426533/d278cd77-f26c-440f-89ac-d0af1e99bf30)


![image](https://github.com/webmin/authentic-theme/assets/4426533/735fb91a-34ac-44a7-940b-5f3b7470f347)

**Comment by michaelbaisch** [comment]
Awesome, thanks!
