### ISSUE TITLE
How to force UTF-8 charset... ?

### ISSUE THREAD

**Issue by 7starsone** [webmin/authentic-theme#27]
hi,
your theme adds `<meta charset="utf-8">` to the html source and this is good

but why Chrome automatically selects ISO-8859-1 ?

why in /usr/libexec/webmin/virtual-server/lang there are only cz.UTF-8, zh_CN.UTF-8 and zh_TW.UTF-8 and the other languages have no utf-8 versions?
i tried to save a language file to UTF-8 and add it lang.UTF-8 but here i can't select Virtualmin only language... what's the option to choose to force utf-8 everywhere?

to me this method is too difficult and they should correct soon
Webmin/Virtualmin/Usermin they all should be done to support UTF-8 easily...

anyway, do you know how to do a workaround?
thanks

**Comment by anirbanchakrabarty** [comment]
hi, when i am running this file voa terminal,it works but not as a
scheduled cron job. in that case i am receiving the error already
given.
attached is the file in current locale as UTF-8.the other option is iso-8859-1.
thank you

[image]
Virus-free. www.avg.com

On Sat, Nov 17, 2018 at 11:56 AM Ilia Rostovtsev
<notifications@github.com> wrote:
>
> Can you attach a file which you're having the problem is? Do you output this as JSON, or ordinary file?
>
> What is the output of browser's console of the following command:
>
> get_server_data('charset')
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.[image]



--
"The more u sweat in d practice...... d less u bleed in d battle
field." Let our work be so strong, that even d goal tends to see us
winning...
https://fedoraproject.org/wiki/Distribution/FreeMedia/India/LocalContacts#List
https://fedoraproject.org/wiki/User:Anirbanchakrabarty
Invincible

**Comment by anirbanchakrabarty** [comment]
Did you receive my email friend?

**Comment by anirbanchakrabarty** [comment]
#!/bin/bash
/usr/local/bin/googler -n 40 -C --np aquaball> result.txt
cm=$(grep 'EHEIM aquaball 130 - Aquaristikshop' result.txt | awk '{print $1}')
echo $cm
(sleep 5;echo $cm;sleep 2)|/usr/local/bin/googler -n 40 --nocolor aquaball
exit ;




SAVE the above in a file say scripts.sh and run in webmin.

**Comment by anirbanchakrabarty** [comment]
The error is as follows:

stdout encoding 'ascii' detected. googler requires utf-8 to work properly. The wrong encoding may be due to a non-UTF-8 locale or an improper PYTHONIOENCODING. (For the record, your locale language is and locale encoding is ; your PYTHONIOENCODING is not set.)

Please set a UTF-8 locale (e.g., en_US.UTF-8) or set PYTHONIOENCODING to utf-8.

**Comment by anirbanchakrabarty** [comment]
The error is as follows:

stdout encoding 'ascii' detected. googler requires utf-8 to work properly. The wrong encoding may be due to a non-UTF-8 locale or an improper PYTHONIOENCODING. (For the record, your locale language is and locale encoding is ; your PYTHONIOENCODING is not set.)

Please set a UTF-8 locale (e.g., en_US.UTF-8) or set PYTHONIOENCODING to utf-8.

**Comment by anirbanchakrabarty** [comment]
my locale output is as under:
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=

**Comment by anirbanchakrabarty** [comment]
> export LANG=C.UTF-8

same error: stdout encoding 'ascii' detected. googler requires utf-8 to work properly. The wrong encoding may be due to a non-UTF-8 locale or an improper PYTHONIOENCODING. (For the record, your locale language is and locale encoding is ; your PYTHONIOENCODING is not set.)

Please set a UTF-8 locale (e.g., en_US.UTF-8) or set PYTHONIOENCODING to utf-8.

**Comment by anirbanchakrabarty** [comment]
> What is the output of
> locale
> From inside the script when run from console and as Webmin Cron job?

what did you mean by this ?thanks
